


spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/db
    username: root
    password: pass
    pool:
      initial-size: 10
      validation-query: select 1

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG